#!/usr/bin/env python3
"""Unified D&D randomization — items, characters, worlds, tables, total chaos."""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "dnd-utils" / "scripts"))

from bootstrap import ensure_utils_importable

ensure_utils_importable()

from class_progression import build_multiclass_plan, calculate_spell_slots  # noqa: E402
from dnd_state_utils import (  # noqa: E402
    get_kingdom_state,
    get_world_state,
    load_json,
    save_json,
    update_kingdom_state,
    update_world_state,
)
from event_system import record_event  # noqa: E402
from paths import get_campaign_path  # noqa: E402

from randomizer_data import (  # noqa: E402
    ALIGNMENTS,
    BACKGROUNDS,
    CLASSES,
    FEATS,
    PERSON_FIRST,
    PERSON_LAST,
    RACES,
    SPELLS_BY_LEVEL,
    WORLD_DOMAINS,
    RANDOMIZER_DATA_VERSION,
)
from randomizer_engine import (  # noqa: E402
    add_custom_entry,
    ledger_summary,
    list_tables,
    roll_table,
    weighted_pick,
    ENGINE_VERSION,
)

RANDOMIZER_VERSION = "4.1.0"


def _rng(seed: Optional[int] = None) -> random.Random:
    return random.Random(seed)


def _roll_stats(rng: random.Random) -> Dict[str, int]:
    stats = {}
    for abbr in ("str", "dex", "con", "int", "wis", "cha"):
        rolls = sorted(rng.randint(1, 6) for _ in range(4))
        stats[abbr] = sum(rolls[1:])
    return stats


def random_name(*, name_type: str = "person", seed: Optional[int] = None) -> Dict[str, Any]:
    rng = _rng(seed)
    if name_type == "place":
        name = f"{rng.choice(PERSON_FIRST)}{rng.choice(['vale', 'ford', 'haven', 'spire'])}"
    elif name_type == "tavern":
        name = f"The {rng.choice(['Prancing', 'Gilded', 'Weary', 'Broken', 'Laughing'])} {rng.choice(['Stag', 'Dragon', 'Mug', 'Crown', 'Rat'])}"
    else:
        name = f"{rng.choice(PERSON_FIRST)} {rng.choice(PERSON_LAST)}"
    return {"type": name_type, "name": name, "version": RANDOMIZER_VERSION}


def random_item(
    *,
    level: int = 5,
    magic_chance: float = 0.35,
    seed: Optional[int] = None,
    campaign_name: Optional[str] = None,
) -> Dict[str, Any]:
    rng = _rng(seed)
    if campaign_name:
        table = "magic_item" if rng.random() < magic_chance else "mundane_item"
        rolled = roll_table(table, campaign_name=campaign_name, count=1, seed=seed, use_ledger=True)
        if "results" in rolled:
            item = rolled["results"][0]
            return {"item": item, "table": table, "level": level, "version": RANDOMIZER_VERSION}
    from randomizer_data import MAGIC_ITEMS, MUNDANE_ITEMS  # noqa: E402

    pool = MAGIC_ITEMS if rng.random() < magic_chance else MUNDANE_ITEMS
    item = weighted_pick(pool, rng=rng)
    return {"item": item, "magic": pool is MAGIC_ITEMS, "level": level, "version": RANDOMIZER_VERSION}


def random_character(
    *,
    level: int = 1,
    multiclass: bool = False,
    seed: Optional[int] = None,
) -> Dict[str, Any]:
    rng = _rng(seed)
    race = rng.choice(RACES)
    background = rng.choice(BACKGROUNDS)
    alignment = rng.choice(ALIGNMENTS)
    stats = _roll_stats(rng)
    name = random_name(seed=rng.randint(0, 999999))["name"]

    primary = rng.choice(CLASSES)
    classes = [{"name": primary, "level": level}]
    if multiclass and level >= 2:
        second = rng.choice([c for c in CLASSES if c != primary])
        split = rng.randint(1, level - 1)
        classes = [
            {"name": primary, "level": level - split},
            {"name": second, "level": split},
        ]

    feats = []
    if level >= 4 and rng.random() < 0.5:
        feats.append({"name": rng.choice(FEATS), "source": "random"})

    known_spells = []
    caster = primary.lower() in ("wizard", "sorcerer", "cleric", "druid", "bard", "warlock", "paladin", "ranger")
    if caster:
        for lvl, spells in SPELLS_BY_LEVEL.items():
            if lvl <= min(3, level // 2 + 1):
                known_spells.append(rng.choice(spells))

    slots = calculate_spell_slots(classes)
    char = {
        "name": name,
        "race": race,
        "background": background,
        "alignment": alignment,
        "classes": classes,
        "level": level,
        "stats": stats,
        "proficiency_bonus": 2 + ((level - 1) // 4),
        "hit_points": {"current": 10 + level * 6, "max": 10 + level * 6, "temp": 0},
        "feats": feats,
        "inventory": [random_item(level=level, seed=rng.randint(0, 999999))["item"]],
        "spell_slots": {"max": slots.get("slots", {}), "used": {}} if slots.get("slots") else None,
        "known_spells": known_spells,
        "notes": "Generated by dnd-randomizer",
        "homebrew": {"randomized": True},
    }
    char["build_plan"] = build_multiclass_plan(classes)
    return {"character": char, "version": RANDOMIZER_VERSION}


def random_npc(*, seed: Optional[int] = None, campaign_name: Optional[str] = None) -> Dict[str, Any]:
    rng = _rng(seed)
    role_roll = roll_table("npc_role", campaign_name=campaign_name, seed=seed) if campaign_name else None
    role = role_roll["results"][0]["name"] if role_roll and role_roll.get("results") else rng.choice(
        ["merchant", "guard", "sage"]
    )
    name = random_name(seed=rng.randint(0, 999999))["name"]
    return {
        "npc": {
            "name": name,
            "role": role,
            "race": rng.choice(RACES),
            "alignment": rng.choice(ALIGNMENTS),
            "trait": rng.choice(["secretive", "boisterous", "melancholy", "paranoid", "charming"]),
            "motivation": rng.choice(["profit", "revenge", "redemption", "knowledge", "power"]),
            "quirk": rng.choice(["never sits", "quotes poetry", "afraid of birds", "collects teeth"]),
        },
        "version": RANDOMIZER_VERSION,
    }


def random_world(*, seed: Optional[int] = None, campaign_name: Optional[str] = None) -> Dict[str, Any]:
    rng = _rng(seed)
    domain = rng.choice(WORLD_DOMAINS)
    location = f"{rng.choice(['North', 'South', 'East', 'West'])}ern {domain}"

    def _tbl(name: str) -> str:
        if campaign_name:
            r = roll_table(name, campaign_name=campaign_name, count=1, seed=rng.randint(0, 999999))
            if r.get("results"):
                return r["results"][0]["name"]
        return roll_table(name, count=1, seed=rng.randint(0, 999999))["results"][0]["name"]

    world = {
        "domain_name": domain,
        "current_location": location,
        "weather": _tbl("weather"),
        "terrain": _tbl("terrain"),
        "government": _tbl("government"),
        "threat": _tbl("world_threat"),
        "hook": _tbl("quest_hook"),
        "in_game_time": rng.choice(["dawn", "midday", "dusk", "midnight"]),
        "mode": rng.choice(["tabletop", "sandbox", "kingdom"]),
        "notes": "Random world seed from dnd-randomizer",
    }
    factions = {
        rng.choice(["locals", "merchants", "militia", "cult", "nobles"]): {
            "influence": rng.randint(1, 30),
            "attitude": rng.choice(["friendly", "neutral", "hostile", "wary"]),
            "goals": [rng.choice(["expand_trade", "secure_borders", "seek_alliance"])],
        }
    }
    return {
        "world": world,
        "kingdom": {
            "domain_name": domain,
            "resources": {
                "gold": rng.randint(100, 2000),
                "food": rng.randint(50, 500),
                "materials": rng.randint(20, 300),
            },
            "factions": factions,
            "population": rng.randint(500, 50000),
        },
        "version": RANDOMIZER_VERSION,
    }


def random_encounter(*, party_level: int = 3, seed: Optional[int] = None) -> Dict[str, Any]:
    rng = _rng(seed)
    terrain = roll_table("terrain", count=1, seed=seed)["results"][0]["name"]
    feature = roll_table("dungeon_feature", count=1, seed=rng.randint(0, 999999))["results"][0]["name"]
    num_foes = rng.randint(1, 4)
    cr_each = max(0.25, party_level / num_foes * rng.uniform(0.5, 1.2))
    foes = [
        {
            "name": rng.choice(["Goblin", "Bandit", "Wolf", "Skeleton", "Cultist", "Stirge"]),
            "cr": round(cr_each, 2),
            "count": rng.randint(1, 3),
        }
        for _ in range(num_foes)
    ]
    return {
        "party_level": party_level,
        "terrain": terrain,
        "feature": feature,
        "complication": roll_table("travel_complication", count=1, seed=rng.randint(0, 999999))["results"][0]["name"],
        "foes": foes,
        "version": RANDOMIZER_VERSION,
    }


def random_feat(*, seed: Optional[int] = None) -> Dict[str, Any]:
    rng = _rng(seed)
    return {"feat": rng.choice(FEATS), "version": RANDOMIZER_VERSION}


def random_spell(*, max_level: int = 3, seed: Optional[int] = None) -> Dict[str, Any]:
    rng = _rng(seed)
    level = rng.randint(0, min(max_level, 3))
    spell = rng.choice(SPELLS_BY_LEVEL.get(level, SPELLS_BY_LEVEL[0]))
    return {"spell": spell, "level": level, "version": RANDOMIZER_VERSION}


def random_quest(*, seed: Optional[int] = None, campaign_name: Optional[str] = None) -> Dict[str, Any]:
    rng = _rng(seed)
    hook = roll_table("quest_hook", campaign_name=campaign_name, count=1, seed=seed)
    hook_text = hook["results"][0]["name"] if hook.get("results") else "Unknown quest"
    return {
        "quest": {
            "title": hook_text[:60],
            "hook": hook_text,
            "urgency": rng.choice(["low", "medium", "high"]),
            "reward_hint": random_item(level=rng.randint(1, 10), seed=rng.randint(0, 999999))["item"]["name"],
        },
        "version": RANDOMIZER_VERSION,
    }


def random_everything(
    campaign_name: Optional[str] = None,
    *,
    level: int = 3,
    seed: Optional[int] = None,
) -> Dict[str, Any]:
    rng = _rng(seed)
    s = lambda: rng.randint(0, 999999)
    package = {
        "character": random_character(level=level, multiclass=rng.random() < 0.3, seed=s())["character"],
        "npc": random_npc(campaign_name=campaign_name, seed=s())["npc"],
        "world": random_world(campaign_name=campaign_name, seed=s()),
        "encounter": random_encounter(party_level=level, seed=s()),
        "item": random_item(level=level, campaign_name=campaign_name, seed=s()),
        "quest": random_quest(campaign_name=campaign_name, seed=s())["quest"],
        "feat": random_feat(seed=s())["feat"],
        "spell": random_spell(seed=s()),
        "name_place": random_name(name_type="place", seed=s()),
        "version": RANDOMIZER_VERSION,
    }
    return package


def apply_character(campaign_name: str, *, seed: Optional[int] = None, level: int = 1) -> Dict[str, Any]:
    gen = random_character(level=level, multiclass=level > 1, seed=seed)
    char = gen["character"]
    path = get_campaign_path(campaign_name) / "state" / "player_character.json"
    save_json(path, char)
    record_event(campaign_name, f"Random character applied: {char['name']}", tags=["randomizer", "character"])
    return {"applied": str(path), "character": char, "version": RANDOMIZER_VERSION}


def apply_world(campaign_name: str, *, seed: Optional[int] = None) -> Dict[str, Any]:
    gen = random_world(campaign_name=campaign_name, seed=seed)
    update_world_state(campaign_name, gen["world"])
    update_kingdom_state(campaign_name, gen["kingdom"])
    record_event(campaign_name, f"Random world applied: {gen['world']['domain_name']}", tags=["randomizer", "world"])
    return {"world": gen["world"], "kingdom": gen["kingdom"], "version": RANDOMIZER_VERSION}


def main() -> None:
    parser = argparse.ArgumentParser(description="Unified D&D randomizer")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_list = sub.add_parser("list-tables")
    p_list.add_argument("campaign", nargs="?")

    p_roll = sub.add_parser("roll-table")
    p_roll.add_argument("table")
    p_roll.add_argument("campaign", nargs="?")
    p_roll.add_argument("--count", type=int, default=1)
    p_roll.add_argument("--seed", type=int)
    p_roll.add_argument("--no-ledger", action="store_true")

    p_item = sub.add_parser("random-item")
    p_item.add_argument("campaign", nargs="?")
    p_item.add_argument("--level", type=int, default=5)
    p_item.add_argument("--seed", type=int)

    p_char = sub.add_parser("random-character")
    p_char.add_argument("--level", type=int, default=1)
    p_char.add_argument("--multiclass", action="store_true")
    p_char.add_argument("--seed", type=int)

    p_npc = sub.add_parser("random-npc")
    p_npc.add_argument("campaign", nargs="?")
    p_npc.add_argument("--seed", type=int)

    p_world = sub.add_parser("random-world")
    p_world.add_argument("campaign", nargs="?")
    p_world.add_argument("--seed", type=int)

    p_enc = sub.add_parser("random-encounter")
    p_enc.add_argument("--party-level", type=int, default=3)
    p_enc.add_argument("--seed", type=int)

    p_name = sub.add_parser("random-name")
    p_name.add_argument("--type", default="person", choices=["person", "place", "tavern"])
    p_name.add_argument("--seed", type=int)

    p_feat = sub.add_parser("random-feat")
    p_feat.add_argument("--seed", type=int)

    p_spell = sub.add_parser("random-spell")
    p_spell.add_argument("--max-level", type=int, default=3)
    p_spell.add_argument("--seed", type=int)

    p_quest = sub.add_parser("random-quest")
    p_quest.add_argument("campaign", nargs="?")
    p_quest.add_argument("--seed", type=int)

    p_all = sub.add_parser("random-everything")
    p_all.add_argument("campaign", nargs="?")
    p_all.add_argument("--level", type=int, default=3)
    p_all.add_argument("--seed", type=int)

    p_apply_c = sub.add_parser("apply-character")
    p_apply_c.add_argument("campaign")
    p_apply_c.add_argument("--level", type=int, default=1)
    p_apply_c.add_argument("--seed", type=int)

    p_apply_w = sub.add_parser("apply-world")
    p_apply_w.add_argument("campaign")
    p_apply_w.add_argument("--seed", type=int)

    p_ledger = sub.add_parser("ledger")
    p_ledger.add_argument("campaign")
    p_ledger.add_argument("--limit", type=int, default=20)

    p_add = sub.add_parser("add-table-entry")
    p_add.add_argument("campaign")
    p_add.add_argument("table")
    p_add.add_argument("name")
    p_add.add_argument("--weight", type=int, default=1)

    args = parser.parse_args()

    if args.cmd == "list-tables":
        result = list_tables(args.campaign)
    elif args.cmd == "roll-table":
        result = roll_table(
            args.table,
            campaign_name=args.campaign,
            count=args.count,
            seed=args.seed,
            use_ledger=not args.no_ledger,
        )
    elif args.cmd == "random-item":
        result = random_item(level=args.level, seed=args.seed, campaign_name=args.campaign)
    elif args.cmd == "random-character":
        result = random_character(level=args.level, multiclass=args.multiclass, seed=args.seed)
    elif args.cmd == "random-npc":
        result = random_npc(seed=args.seed, campaign_name=args.campaign)
    elif args.cmd == "random-world":
        result = random_world(seed=args.seed, campaign_name=args.campaign)
    elif args.cmd == "random-encounter":
        result = random_encounter(party_level=args.party_level, seed=args.seed)
    elif args.cmd == "random-name":
        result = random_name(name_type=args.type, seed=args.seed)
    elif args.cmd == "random-feat":
        result = random_feat(seed=args.seed)
    elif args.cmd == "random-spell":
        result = random_spell(max_level=args.max_level, seed=args.seed)
    elif args.cmd == "random-quest":
        result = random_quest(seed=args.seed, campaign_name=args.campaign)
    elif args.cmd == "random-everything":
        result = random_everything(args.campaign, level=args.level, seed=args.seed)
    elif args.cmd == "apply-character":
        result = apply_character(args.campaign, seed=args.seed, level=args.level)
    elif args.cmd == "apply-world":
        result = apply_world(args.campaign, seed=args.seed)
    elif args.cmd == "ledger":
        result = ledger_summary(args.campaign, limit=args.limit)
    elif args.cmd == "add-table-entry":
        result = add_custom_entry(args.campaign, args.table, args.name, weight=args.weight)
    else:
        result = {"error": "unknown command"}

    result.setdefault("data_version", RANDOMIZER_DATA_VERSION)
    result.setdefault("engine_version", ENGINE_VERSION)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()